# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'HappyBuy' do
    
    
    pod 'AFNetworking'
    pod 'YYKit' 
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'BlocksKit'
    pod 'CocoaLumberjack'
    pod 'MBProgressHUD'
    pod 'TPKeyboardAvoiding'
    pod 'MLTransition'


end

